epicsEnvSet("COMBINED_HOMING_MODES",0)
epicsEnvSet("AXIS_MODE_MULTIPLIER",1)
calc("COMBINED_HOMING_MODES", "$(COMBINED_HOMING_MODES)+$(AXIS_MODE_MULTIPLIER)*$(HOME$(MN)=1)", 1, 0)
calc("AXIS_MODE_MULTIPLIER", "$(NUMBER_HOME_MODES)*$(AXIS_MODE_MULTIPLIER)", 1, 0)
