stringiftest("ALIASED", "$(CHAN$(CHAN)NAME=)", 3, "")

dbLoadRecords("${TOP}/db/moxa1210_aliases.db","P=$(MYPVPREFIX)$(IOCNAME), NAME=$(MYPVPREFIX)$(IOCNAME), ASYNPORT=$(E12XX_ASYNPORT), CHANNAME=$(CHAN$(CHAN)NAME=), IFALIASED=$(IFALIASED), IFNOTALIASED=$(IFNOTALIASED), CHAN=$(CHAN)")
