stringiftest("ALIASED", "$(CHAN$(CHAN)NAME=)", 3, "")

dbLoadRecords("${TOP}/db/moxa12XX_aliases.db","P=$(MYPVPREFIX)$(IOCNAME), NAME=$(MYPVPREFIX)$(IOCNAME), ASYNPORT=$(E12XX_ASYNPORT), CHANNAME=$(CHAN$(CHAN)NAME=), FNCTN=$(FNCTN), IFALIASED=$(IFALIASED), IFNOTALIASED=$(IFNOTALIASED), CHAN=$(CHAN)")

$(IFMOXA1240) $(IFALIASED) dbLoadRecords("${TOP}/db/moxa_e1240_misc.db","NAME=$(MYPVPREFIX)$(IOCNAME), P=$(MYPVPREFIX)$(IOCNAME), ASYNPORT=$(E12XX_ASYNPORT), CHAN=$(CHAN)")

$(IFMOXA1262) $(IFALIASED) dbLoadRecords("${TOP}/db/moxa_e1262_misc.db","NAME=$(MYPVPREFIX)$(IOCNAME), P=$(MYPVPREFIX)$(IOCNAME), ASYNPORT=$(E12XX_ASYNPORT), CHAN=$(CHAN)")
