##ISIS## Run IOC initialisation 
< $(IOCSTARTUP)/init.cmd

# The search path for database files
epicsEnvSet("EPICS_DB_INCLUDE_PATH", "$(ADCORE)/db")
epicsEnvSet("PREFIX", "$(MYPVPREFIX)$(IOCNAME):")
epicsEnvSet("PORT", "SP1")

asynSetMinTimerPeriod(0.001)

## Load record instances

##ISIS## Load common DB records 
< $(IOCSTARTUP)/dbload.cmd

#Load in camera-specific dbs and set appropriate macros. note that XSIZE and YSIZE must be set for later DB loads to work
epicsEnvSet("CAMFILE", "$(TOP)/iocBoot/$(IOC)/devices/pearlcam")
< $(CAMFILE).cmd

stringiftest("CROSSHAIR", "$(CROSSHAIR_X=)")

NDROIConfigure("ROI1", 3, 0, "$(PORT)", 0, 0)
NDStatsConfigure("Stats1", 3, 0, "ROI1", 0, 0)
NDTimeSeriesConfigure("Stats1_TS", 100, 0, "Stats1", 0, 22, 0, 0, 0, 0)
## add one overlay for our crosshair
NDOverlayConfigure("OVER1", 3, 0, "ROI1", 0, 1)
NDStdArraysConfigure("Image1", 3, 0, "OVER1", 0, 0)
NDPvaConfigure("PVA1", 3, 0, "OVER1", 0, "$(PREFIX)PVA1:IMAGE", 0)

# Load the autogenerated file of GenICam features
$(IFNOTDEVSIM) dbLoadRecords("$(GENICAM_DB_FILE)", "P=$(PREFIX),R=CAM1:,PORT=$(PORT)")

# Use this line for 8-bit or 16-bit data
dbLoadRecords("$(ADCORE)/db/NDStdArrays.template", "P=$(PREFIX),R=IMAGE1:,PORT=Image1,ADDR=0,TIMEOUT=1,NDARRAY_PORT=OVER1,TYPE=Int16,DATATYPE=3,FTVL=USHORT,NELEMENTS=$(NELEMENTS),ENABLED=1")
dbLoadRecords("NDROI.template", "P=$(PREFIX),R=ROI1:,PORT=ROI1,ADDR=0,TIMEOUT=1,DATATYPE=3,NDARRAY_PORT=$(PORT),ENABLED=1")
dbLoadRecords("NDStats.template", "P=$(PREFIX),R=STATS1:,PORT=Stats1,ADDR=0,TIMEOUT=1,NDARRAY_PORT=ROI1,DATATYPE=3,FTVL=SHORT,ENABLED=1,NCHANS=1,XSIZE=$(XSIZE),YSIZE=$(YSIZE),HIST_SIZE=1")
# loading this gives callback errors, need to investigate more
#dbLoadRecords("NDTimeSeries.template", "P=$(PREFIX),R=STATS1:TS:, PORT=Stats1_TS,ADDR=0,TIMEOUT=1,NDARRAY_PORT=Stats1,NDARRAY_ADDR=0,NCHANS=$(NCHANS),ENABLED=1")
dbLoadRecords("NDPva.template", "P=$(PREFIX),R=PVA1:,DATATYPE=3,PORT=PVA1,ADDR=0,TIMEOUT=1,NDARRAY_PORT=OVER1,ENABLED=1")

## add overlay
dbLoadRecords("NDOverlay.template", "P=$(PREFIX),R=OVER1:,PORT=OVER1,ADDR=0,DATATYPE=3,TIMEOUT=1,NDARRAY_PORT=ROI1,ENABLED=1")
# overlay crosshair - we set size via dbpf later
dbLoadRecords("NDOverlayN.template", "P=$(PREFIX),R=OVER1:1:,NAME=OVRL1,SHAPE=0,O=OVER1:,PORT=OVER1,ADDR=0,TIMEOUT=1")

##ISIS## Stuff that needs to be done after all records are loaded but before iocInit is called 
< $(IOCSTARTUP)/preiocinit.cmd

cd "${TOP}/iocBoot/${IOC}"
iocInit

## Start any sequence programs
#seq sncxxx,"user=faa59"

##ISIS## Stuff that needs to be done after iocInit is called e.g. sequence programs 
< $(IOCSTARTUP)/postiocinit.cmd

create_monitor_set("$(IOCNAME)_settings.req", 30, "P=$(PREFIX)")

# Set any dbpfs ie. exposure mode, this defaults to CAMFILE_dbpfs. 
< $(DBPFS_FILE=$(CAMFILE)_dbpfs).cmd

$(IFDEVSIM) dbpf "$(PREFIX)CAM1:AcquirePeriod", "0.5"
$(IFDEVSIM) dbpf "$(PREFIX)CAM1:Offset", 50
$(IFDEVSIM) dbpf "$(PREFIX)CAM1:Noise", 40
# bug in simulator in that you need to swap out and back to make it pick up
# offset+noise correctly
$(IFDEVSIM) dbpf "$(PREFIX)CAM1:SimMode", "LinearRamp"
epicsThreadSleep(1.0)
$(IFDEVSIM) dbpf "$(PREFIX)CAM1:SimMode", "Offset&Noise"
