install:
	echo Nothing to be done for install

clean:
	echo Nothing to be done for clean

distclean:
	echo Nothing to be done for distclean

uninstall:
	echo Nothing to be done for uninstall

runtests:
	echo Nothing to be done for runtests
