TOP=../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
#  Optimization of db files using dbst (DEFAULT: NO)
#DB_OPT = YES

#----------------------------------------------------
# Create and install (or just install) into <top>/db
# databases, templates, substitutions like this
DB += devEurothrmA01.db
DB += devEurothrmA02.db
DB += devEurothrmA03.db
DB += devEurothrmA04.db
DB += devEurothrmA05.db
DB += devEurothrmA06.db
DB += devEurothrmA07.db
DB += devEurothrmA08.db
DB += devEurothrmA09.db
DB += devEurothrmA010.db
DB += devSimDis.db
DB += isActiveEurothrm.db

#----------------------------------------------------
# If <anyname>.db template is not named <anyname>*.template add
# <anyname>_template = <templatename>

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

