# $(ICPCONFIGDIR) or $(ICPCONFIGROOT) ?
epicsEnvSet "LOOKUPFILE1" "$(ICPCONFIGROOT)/motionSetPoints/monitor3.txt"
epicsEnvSet "LOOKUPFILE2" "$(ICPCONFIGROOT)/motionSetPoints/monitor4.txt"
epicsEnvSet "LOOKUPFILE3" "$(ICPCONFIGROOT)/motionSetPoints/sample_x.txt"
epicsEnvSet "LOOKUPFILE4" "$(ICPCONFIGROOT)/motionSetPoints/sample_y.txt"

dbLoadRecords("$(MOTIONSETPOINTS)/db/motionSetPoints.db","P=$(MYPVPREFIX)LKUP:MON3:,NP=100,TARGET_PV1=$(MYPVPREFIX)MTR0101,TARGET_RBV1=$(MYPVPREFIX)MTR0101.RBV,TARGET_DONE=$(MYPVPREFIX)MTR0101.DMOV,TOL=1,LOOKUP=LOOKUPFILE1")
dbLoadRecords("$(MOTIONSETPOINTS)/db/motionSetPoints.db","P=$(MYPVPREFIX)LKUP:MON4:,NP=100,TARGET_PV1=$(MYPVPREFIX)MTR0102,TARGET_RBV1=$(MYPVPREFIX)MTR0102.RBV,TARGET_DONE=$(MYPVPREFIX)MTR0102.DMOV,TOL=1,LOOKUP=LOOKUPFILE2")
dbLoadRecords("$(MOTIONSETPOINTS)/db/motionSetPoints.db","P=$(MYPVPREFIX)LKUP:SAMPX:,NP=100,TARGET_PV1=$(MYPVPREFIX)MTR0103,TARGET_RBV1=$(MYPVPREFIX)MTR0103.RBV,TARGET_DONE=$(MYPVPREFIX)MTR0103.DMOV,FILTER_SRC=$(MYPVPREFIX)LKUP:SAMPY:FILTER:OUT,TOL=1,LOOKUP=LOOKUPFILE3")
dbLoadRecords("$(MOTIONSETPOINTS)/db/motionSetPoints.db","P=$(MYPVPREFIX)LKUP:SAMPY:,NP=100,TARGET_PV1=$(MYPVPREFIX)MTR0104,TARGET_RBV1=$(MYPVPREFIX)MTR0104.RBV,TARGET_DONE=$(MYPVPREFIX)MTR0104.DMOV,TOL=1,LOOKUP=LOOKUPFILE4")
