# $(ICPCONFIGDIR) or $(ICPCONFIGROOT) ?
epicsEnvSet "LOOKUPFILE1" "$(ICPCONFIGROOT)/motionSetPoints/monitor3.txt"
epicsEnvSet "LOOKUPFILE2" "$(ICPCONFIGROOT)/motionSetPoints/monitor4.txt"
epicsEnvSet "LOOKUPFILE3" "$(ICPCONFIGROOT)/motionSetPoints/sample_x.txt"
epicsEnvSet "LOOKUPFILE4" "$(ICPCONFIGROOT)/motionSetPoints/sample_y.txt"

motionSetPointsConfigure("LOOKUPFILE1","LOOKUPFILE1")
motionSetPointsConfigure("LOOKUPFILE2","LOOKUPFILE2")
motionSetPointsConfigure("LOOKUPFILE3","LOOKUPFILE3")
motionSetPointsConfigure("LOOKUPFILE4","LOOKUPFILE4")

dbLoadRecords("$(MOTIONSETPOINTS)/db/motionSetPoints.db","P=$(MYPVPREFIX)LKUP:MON3:,TARGET_PV1=$(MYPVPREFIX)MOT:MTR0601,TARGET_RBV1=$(MYPVPREFIX)MOT:MTR0601.RBV,TARGET_DONE=$(MYPVPREFIX)MOT:MTR0601.DMOV,TOL=1,LOOKUP=LOOKUPFILE1")
dbLoadRecords("$(MOTIONSETPOINTS)/db/motionSetPoints.db","P=$(MYPVPREFIX)LKUP:MON4:,TARGET_PV1=$(MYPVPREFIX)MOT:MTR0602,TARGET_RBV1=$(MYPVPREFIX)MOT:MTR0602.RBV,TARGET_DONE=$(MYPVPREFIX)MOT:MTR0602.DMOV,TOL=1,LOOKUP=LOOKUPFILE2")
dbLoadRecords("$(MOTIONSETPOINTS)/db/motionSetPoints.db","P=$(MYPVPREFIX)LKUP:SAMPX:,TARGET_PV1=$(MYPVPREFIX)MOT:MTR0603,TARGET_RBV1=$(MYPVPREFIX)MOT:MTR0603.RBV,TARGET_DONE=$(MYPVPREFIX)MOT:MTR0603.DMOV,FILTER_SRC=$(MYPVPREFIX)LKUP:SAMPY:FILTER:OUT,TOL=1,LOOKUP=LOOKUPFILE3")
dbLoadRecords("$(MOTIONSETPOINTS)/db/motionSetPoints.db","P=$(MYPVPREFIX)LKUP:SAMPY:,TARGET_PV1=$(MYPVPREFIX)MOT:MTR0604,TARGET_RBV1=$(MYPVPREFIX)MOT:MTR0604.RBV,TARGET_DONE=$(MYPVPREFIX)MOT:MTR0604.DMOV,TOL=1,LOOKUP=LOOKUPFILE4")
