PREFIX = $(MYPVPREFIX)MK3CHOPPER
SIMULATION = TRUE
NUM_SIMULATED_CHOPPERS = 2
CONFIGURED_PORT = 5064
CHOPPER_CONFIG = C:\\LabVIEW Modules\\Drivers\\ISIS MK3 Disc Chopper\\MK3_Chopper.config
SERVER_ADDRESS = 127.0.0.1
DATABASE_FILE = C:\\Instrument\\Apps\\EPICS\\iocs.sq3

