## set TEMP_NUM before calling
## if TEMP_NUM = 1 then the entries for TEMP_NUM 1 in this IOC will be used for the setup

stringiftest("SPC_PRESSURE", "$(SPC_PRESSURE_$(TEMP_NUM)=)")

## Load our record instances
$(IFSPC_PRESSURE) dbLoadRecords("$(MERCURY_ITC)/db/MercurySPC.db", "P=$(MYPVPREFIX)$(IOCNAME):,TEMP_CARD=$(TEMP_NUM),PRESSURE_CARD=$(SPC_PRESSURE_$(TEMP_NUM)=),RECSIM=$(RECSIM),DISABLE=$(DISABLE),TEMP_DEADBAND=$(SPC_TEMP_DEADBAND=0.0),MIN_PRESSURE=$(SPC_MIN_PRESSURE=),MAX_PRESSURE=$(SPC_MAX_PRESSURE=),OFFSET=$(SPC_OFFSET=),OFFSET_DURATION=$(SPC_OFFSET_DURATION=),TIMEPV=$(MYPVPREFIX)CS:IOC:$(IOCNAME):DEVIOS:GTIM_TIME,GAIN=$(SPC_GAIN=),CALIB_BASE_DIR=$(CALIB_BASE_DIR), CALIB_DIR=$(CALIB_DIR),SPC_TABLE_FILE=$(SPC_TABLE_FILE=little_blue_cryostat.txt)")

dbLoadRecords("$(MERCURY_ITC)/db/MercurySPCAvailable.db", "P=$(MYPVPREFIX)$(IOCNAME):,TEMP_CARD=$(TEMP_NUM),IFSPC_PRESSURE=$(IFSPC_PRESSURE),IFNOTSPC_PRESSURE=$(IFNOTSPC_PRESSURE)")
