## set TEMP_NUM before calling
## if TEMP_NUM = 1 then the entries for TEMP_NUM 1 in this IOC will be used for the setup

stringiftest("FLOW_SPC_PRESSURE", "$(FLOW_SPC_PRESSURE_$(TEMP_NUM)=)")

## Load our record instances
$(IFFLOW_SPC_PRESSURE) dbLoadRecords("$(MERCURY_ITC)/db/MercuryFlowSPC.db", "P=$(MYPVPREFIX)$(IOCNAME):,TEMP_CARD=$(TEMP_NUM),PRESSURE_CARD=$(FLOW_SPC_PRESSURE_$(TEMP_NUM)=),RECSIM=$(RECSIM),DISABLE=$(DISABLE),TEMP_DEADBAND=$(FLOW_SPC_TEMP_DEADBAND=0.0),MIN_PRESSURE=$(FLOW_SPC_MIN_PRESSURE=),MAX_PRESSURE=$(FLOW_SPC_MAX_PRESSURE=),OFFSET=$(FLOW_SPC_OFFSET=),OFFSET_DURATION=$(FLOW_SPC_OFFSET_DURATION=),TIMEPV=$(MYPVPREFIX)CS:IOC:$(IOCNAME):DEVIOS:GTIM_TIME,GAIN=$(FLOW_SPC_GAIN=),CALIB_BASE_DIR=$(CALIB_BASE_DIR), CALIB_DIR=$(CALIB_DIR),SPC_TABLE_FILE=$(FLOW_SPC_TABLE_FILE=little_blue_cryostat.txt)")

dbLoadRecords("$(MERCURY_ITC)/db/MercurySPCAvailable.db", "P=$(MYPVPREFIX)$(IOCNAME):,TEMP_CARD=$(TEMP_NUM),IFFLOW_SPC_PRESSURE=$(IFFLOW_SPC_PRESSURE),IFNOTFLOW_SPC_PRESSURE=$(IFNOTFLOW_SPC_PRESSURE)")
