## set TEMP_NUM before calling
## if TEMP_NUM = 1 then the entries for TEMP_NUM 1 in this IOC will be used for the setup

stringiftest("FLOW_SPC_PRESSURE_$(TEMP_NUM)", "$(SPC_TYPE_$(TEMP_NUM)=NONE)", 5, "FLOW")
stringiftest("VTI_SPC_PRESSURE_$(TEMP_NUM)", "$(SPC_TYPE_$(TEMP_NUM)=NONE)", 5, "VTI")

epicsEnvSet "VTI_CALIB_BASE_DIR" "$(ICPCONFIGBASE)/$(INSTRUMENT)"
epicsEnvSet "VTI_SENS_DIR" "calib/mercury_vti_spc"

## Load our record instances
$(IFFLOW_SPC_PRESSURE_$(TEMP_NUM)) dbLoadRecords("$(MERCURY_ITC)/db/MercuryFlowSPC.db", "P=$(MYPVPREFIX)$(IOCNAME):,TEMP_CARD=$(TEMP_NUM),PRESSURE_CARD=$(FLOW_SPC_PRESSURE_$(TEMP_NUM)=),RECSIM=$(RECSIM),DISABLE=$(DISABLE),TEMP_DEADBAND=$(FLOW_SPC_TEMP_DEADBAND=0.0),MIN_PRESSURE=$(FLOW_SPC_MIN_PRESSURE=),MAX_PRESSURE=$(FLOW_SPC_MAX_PRESSURE=),OFFSET=$(FLOW_SPC_OFFSET=),OFFSET_DURATION=$(FLOW_SPC_OFFSET_DURATION=),TIMEPV=$(MYPVPREFIX)CS:IOC:$(IOCNAME):DEVIOS:GTIM_TIME,GAIN=$(FLOW_SPC_GAIN=),CALIB_BASE_DIR=$(CALIB_BASE_DIR), CALIB_DIR=$(CALIB_DIR),SPC_TABLE_FILE=$(FLOW_SPC_TABLE_FILE=little_blue_cryostat.txt)")
$(IFVTI_SPC_PRESSURE_$(TEMP_NUM)) dbLoadRecords("$(MERCURY_ITC)/db/MercuryVTISPC.db", "P=$(MYPVPREFIX)$(IOCNAME):,TEMP_CARD=$(TEMP_NUM),PRESSURE_CARD=$(VTI_SPC_PRESSURE_$(TEMP_NUM)=),PRESSURE_CARD_ID=$(PRESSURE_$(VTI_SPC_PRESSURE_$(TEMP_NUM)=)=),MIN_PRESSURE=$(VTI_SPC_MIN_PRESSURE=0.0),MAX_PRESSURE=$(VTI_SPC_MAX_PRESSURE=0.0),PRESSURE_CONSTANT=$(VTI_SPC_PRESSURE_CONSTANT=5.0),PRESSURE_MAX_LKUP=$(VTI_SPC_PRESSURE_MAX_LKUP=None.txt),CALIB_BASE_DIR=$(VTI_CALIB_BASE_DIR),SDIR=$(VTI_SENS_DIR),TEMP_CUTOFF_POINT=$(VTI_SPC_TEMP_CUTOFF_POINT=5.0),TEMP_SCALE=$(VTI_SPC_TEMP_SCALE=2.0),SET_DELAY=$(VTI_SPC_SET_DELAY=10.0),RECSIM=$(RECSIM),DISABLE=$(DISABLE)")



dbLoadRecords("$(MERCURY_ITC)/db/MercurySPCAvailable.db", "P=$(MYPVPREFIX)$(IOCNAME):,TEMP_CARD=$(TEMP_NUM),IFFLOW_SPC_PRESSURE_$(TEMP_NUM)=$(IFFLOW_SPC_PRESSURE_$(TEMP_NUM)),IFNOTFLOW_SPC_PRESSURE_$(TEMP_NUM)=$(IFNOTFLOW_SPC_PRESSURE_$(TEMP_NUM))")
