##ISIS## Run IOC initialisation 
< $(IOCSTARTUP)/init.cmd

# The search path for database files
epicsEnvSet("EPICS_DB_INCLUDE_PATH", "$(ADCORE)/db")
epicsEnvSet("PREFIX", "$(MYPVPREFIX)$(IOCNAME):")
epicsEnvSet("PORT", "SP1")

## Load record instances

##ISIS## Load common DB records 
< $(IOCSTARTUP)/dbload.cmd


#Load in camera-specific dbs and set appropriate macros. note that XSIZE and YSIZE must be set for later DB loads to work
epicsEnvSet("CAMFILE", "$(TOP)/iocBoot/$(IOC)/devices/pearlcam")
< $(CAMFILE).cmd

NDROIConfigure("ROI1", 3, 0, "$(PORT)", 0, 0)
NDStatsConfigure("Stats1", 3, 0, "ROI1", 0, 0)
NDTimeSeriesConfigure("Stats1_TS", 100, 0, "ROI1", 0, 22, 0, 0, 0, 0)
NDStdArraysConfigure("Image1", 3, 0, "ROI1", 0, 0)
NDPvaConfigure("PVA1", 3, 0, "ROI1", 0, "$(PREFIX)PVA1:IMAGE", 0)


# Load the autogenerated file of GenICam features
dbLoadRecords("$(GENICAM_DB_FILE)", "P=$(PREFIX),R=CAM1:,PORT=$(PORT)")

# Use this line for 8-bit or 16-bit data
dbLoadRecords("$(ADCORE)/db/NDStdArrays.template", "P=$(PREFIX),R=IMAGE1:,PORT=Image1,ADDR=0,TIMEOUT=1,NDARRAY_PORT=ROI1,TYPE=Int16,FTVL=SHORT,NELEMENTS=$(NELEMENTS),ENABLED=1")

dbLoadRecords("NDROI.template", "P=$(PREFIX),R=ROI1:,  PORT=ROI1,ADDR=0,TIMEOUT=1,NDARRAY_PORT=$(PORT),ENABLED=1")

dbLoadRecords("NDStats.template", "P=$(PREFIX),R=STATS1:,PORT=Stats1,ADDR=0,TIMEOUT=1,NDARRAY_PORT=ROI1,TYPE=Int16,FTVL=SHORT,ENABLED=1,NCHANS=1,XSIZE=$(XSIZE),YSIZE=$(YSIZE),HIST_SIZE=1")
dbLoadRecords("NDPva.template",  "P=$(PREFIX),R=PVA1:, PORT=PVA1,ADDR=0,TIMEOUT=1,NDARRAY_PORT=ROI1,ENABLED=1")

# Load all other plugins using commonPlugins.cmd
< $(ADCORE)/iocBoot/commonPlugins.cmd


##ISIS## Stuff that needs to be done after all records are loaded but before iocInit is called 
< $(IOCSTARTUP)/preiocinit.cmd

cd "${TOP}/iocBoot/${IOC}"
iocInit

## Start any sequence programs
#seq sncxxx,"user=faa59"

##ISIS## Stuff that needs to be done after iocInit is called e.g. sequence programs 
< $(IOCSTARTUP)/postiocinit.cmd

create_monitor_set("$(IOCNAME)_settings.req", 30, "P=$(PREFIX)")

# Set any dbpfs ie. exposure mode, this defaults to CAMFILE_dbpfs. 
< $(DBPFS_FILE=$(CAMFILE)_dbpfs).cmd

